name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      env:
        IMAGE: "kalemena/connectiq"
        VERSION: "3.1.9-2020-06-24-1cc9d3a70"
      run: |
        docker -v
        docker pull ubuntu:18.04
        docker pull ${IMAGE}:${VERSION} || true
        docker build --pull --cache-from ${IMAGE}:${VERSION} \
          -t ${IMAGE}:${VERSION} \
          -f Dockerfile \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=`git rev-parse --short HEAD` \
          --build-arg VERSION=${VERSION} .
        docker ps -a
        docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
        docker images
        docker login -u "${GITHUB_ACTOR}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push ${IMAGE}:${VERSION}
        docker push ${IMAGE}:latest
        docker logout